# Site settings
title: A11yGoat
email: jazahn@fas.harvard.edu
license: https://github.com/jazahn/A11yGoat/blob/gh-pages/LICENSE.md
description: > # this means to ignore newlines until "baseurl:"
  A11yGoat is an attempt to create a site that contains common accessibility
  flaws with the purpose of teaching how to fix them. This is an open source
  project with no affiliation with any company or institution.
baseurl: "/A11yGoat/" # the subpath of your site, e.g. /blog/
url: "http://jazahn.github.io" # the base hostname & protocol for your site
twitter_username: jazahn
github_username:  jazahn

# Build settings
markdown: kramdown
# GitHub Flavored Markdown
kramdown:
  input: GFM
